### ISSUE TITLE
add grouping option to holdings tree maker

### ISSUE THREAD

**Issue by alioguzhan** [teloscube/decaf-client-javascript-extras#38]
currently `makeValuationReportHoldingsTree` groups holdings by
`classification`. It is default and fixed. We should make it configurable to
group by `classification` or `sector` or `industry` or `country` or `currency`.

https://github.com/teloscube/decaf-client-javascript-extras/blob/f0247da9dde73c028e325df6fa427f79fb9580b2/src/reports/valuation/-valuation-report-holdings-tree/-machinery.ts#L172

**Comment by alioguzhan** [comment]
I am going to steal below section from `headless` folder and integrate it here:

![image](https://github.com/user-attachments/assets/6952702e-4f91-47ba-baf7-804c64208fb9)

@vst Do you have any objection for this ?

**Comment by vst** [comment]
No objection your Honor.

**Comment by vst** [comment]
Niye close ettiysem :)
